[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.4", features = ["v4", "serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_bytes = "0.11.17"
ratatui = "0.29.0"
