services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "chat_app"
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

    environment:
      SERVER_PORT: "${SERVER_PORT}"
      DB_URL: "mongodb://mongo:27017/chatapp"
      TERM: "xterm-256color"

  mongo:
    image: mongo
    container_name: "chat_app_mongo"
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      - DB_URL=true
    logging:
      driver: none
